import argparse
import html
import re

import joblib
from flask import Flask, jsonify, request


def create_app(model_path: str):
    app = Flask(__name__)

    model = joblib.load(model_path)

    def clean_text(s: str) -> str:
        s = "" if s is None else str(s)
        # Match the same cleaning logic used during training as closely as possible
        s = html.unescape(s)
        s = re.sub(r"http\\S+|www\\.\\S+", " URL ", s, flags=re.IGNORECASE)
        s = re.sub(r"\\b\\d+\\b", " NUM ", s)
        s = re.sub(r"<[^>]+>", " ", s)
        s = s.replace("\\n", " ").replace("\\r", " ")
        s = re.sub(r"\\s+", " ", s).strip()
        return s

    def get_spam_probability(text: str) -> float:
        # predict_proba is supported by MultinomialNB + Pipeline
        proba = model.predict_proba([text])[0]
        clf = model.named_steps.get("clf")
        classes = getattr(clf, "classes_", None)

        # If classes are not found for some reason, fall back to index 0
        # NOTE: `classes` is typically a numpy array; `if not classes` raises
        # "truth value of an array is ambiguous".
        if classes is None or len(classes) == 0:
            return float(proba[0])

        classes_list = list(classes)
        if "spam" in classes_list:
            spam_idx = classes_list.index("spam")
            return float(proba[spam_idx])

        # Otherwise return probability of the last class as "spam-like"
        return float(proba[-1])

    @app.get("/health")
    def health():
        return jsonify({"status": "ok"})

    @app.post("/predict")
    def predict():
        payload = request.get_json(silent=True) or {}
        text = payload.get("text", "")
        text = "" if text is None else str(text)

        if not text.strip():
            return jsonify({"error": "Empty text"}), 400

        try:
            text = clean_text(text)
            spam_prob = get_spam_probability(text)
            label = "spam" if spam_prob >= 0.5 else "genuine"
        except Exception as e:
            app.logger.exception("Predict failed")
            return jsonify({"error": "Predict failed", "details": str(e)}), 500

        return jsonify(
            {
                "label": label,
                "spam_probability": spam_prob,
            }
        )

    return app


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model_path",
        required=True,
        help="Path to trained joblib model (Pipeline) generated by train_model.py",
    )
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", default=5000, type=int)
    args = parser.parse_args()

    app = create_app(args.model_path)
    app.run(host=args.host, port=args.port, debug=True)


if __name__ == "__main__":
    main()

